### ISSUE TITLE
Does not work on android

### ISSUE THREAD

**Issue by arshsingh** [andy9775/React-Native-CircularProgress#3]
Has anyone tested this on Android ? I don't think the current approach is going to work, as RN for Android doesn't support individual corner radius properties (borderTopLeftRadius etc.) [1]

This is what I get on Android for the Hollow example code in README:

![screenshot from 2016-01-01 22 16 11](https://cloud.githubusercontent.com/assets/1202179/12071481/baad9760-b0d5-11e5-8475-2f9544309a53.png)

[1] https://github.com/facebook/react-native/issues/3040

**Comment by andy9775** [comment]
Thanks for the heads up, I didn't see the related issues with RN and android. I'll try and get my hands on an android emulator and see if anything can be done. Some quick searching also brought up an issue with `overflow: 'hidden'` not working with a `borderRadius`

**Comment by andy9775** [comment]
You're absolutely right and I apologize that I missed the issue with android not supporting individual corner radius properties. I updated the readme to reflect this for now.
