### ISSUE TITLE
"Unable to resolve module" error

### ISSUE THREAD

**Issue by eduardoboucas** [andy9775/React-Native-CircularProgress#4]
Hi! I've installed the module with `npm install` and I'm requiring it in my code as follows:

``` javascript
var CircularProgressDisplay = require('react-native-progress-circular');
```

However I'm getting the following error:

![screen shot 2016-01-14 at 15 53 09](https://cloud.githubusercontent.com/assets/4162329/12329238/417a9c2e-bad7-11e5-990e-ffd6333a44fa.png)

I even tried manually specifying the whole path to the module directory inside `node_modules`, but it didn't work. Any idea what I might be doing wrong?

Thanks!

**Comment by andy9775** [comment]
Are you using `--save`? If not try running `npm install --save` as shown in the readme

**Comment by andy9775** [comment]
hey @eduardoboucas, I just created a new project using react 0.18 and it works fine for me. Try creating a new project and installing the library again.

**Comment by eduardoboucas** [comment]
I was using `--save` from the beginning, it just didn't work. I ended up manually copying the library to my project (which I needed to do anyway because I wanted to change the functionality a bit).

I'll try to create a new project in the next few days to see if the normal installation procedure works.

Thanks!
