### ISSUE TITLE
Can this be animated?

### ISSUE THREAD

**Issue by arnavyagnik** [andy9775/React-Native-CircularProgress#5]
I like the filled progress bar but can this be animated? or any leads if any1 knows?

**Comment by andy9775** [comment]
I haven't given it a try and I'm not fully certain how it would behave given the way RN treats animations. I'll see if I can set up a small test app in the next few days. In the meantime if you try it, let me know how it goes

**Comment by arnavyagnik** [comment]
I have worked it out , yet it might not be the most sophisticated code but ill let you know once i am at office .
