### ISSUE TITLE
upgrade to react 0.26

### ISSUE THREAD

**Issue by mauron85** [andy9775/React-Native-CircularProgress#6]
Hi, first thank you for the great component. Recently react-native has separated React dependency and as such this plugin is no more compatible. Basically only following lines are necessary to make it work

```
import React, { Component } from 'react';
import {View} from 'react-native';
```

**Comment by andy9775** [comment]
Thanks! I'll take a look as soon as possible and merge it in

**Comment by andy9775** [comment]
Thanks! Closing issue.
